<?php
namespace App\Libraries;


class MessageOfTheDay {
    
    private $messageOfTheDay = array (
        "en" => array(
            "Welcome back! Ready for a productive day?",
            "Log in and make your actions count.",
            "Get ready to chase your dreams!",
            "It's time for action! Log in to get started.",
            "Every login is a step toward success.",
            "Come on, let your day begin!",
            "New opportunities are waiting! Please log in.",
            "Prepare yourself for great achievements!",
            "Log in to realize your great ideas.",
            "It's time to shine! Log in now.",
            "You are closer to your goals. Log in!",
            "Today is your golden opportunity!",
            "Get ready to embrace new challenges!",
            "A small step: log in for great achievements.",
            "Believe in yourself and log in to the future.",
            "Unlock your potential with every session.",
            "Let your vision guide today!",
            "Embrace every moment; log in to make it meaningful.",
            "Your journey to greatness begins with one click.",
            "Strive for progress, not perfection.",
            "A new day, new goals, new opportunities!",
            "Every login is a chance to change.",
            "Seize today and make it yours!",
            "Stay hungry, stay motivated.",
            "Your possibilities are limitless; log in!",
            "Dare to dream and log in to take action.",
            "Motivation is what gets you started.",
            "Build successful habits with every login.",
            "Great things happen outside your comfort zone.",
            "Keep moving forward; you're almost there!",
            "Focus on the goal, not the obstacles.",
            "Log in today and take the first step.",
            "The best time to act is now!",
            "Turn your dreams into a plan.",
            "Your efforts determine your results.",
            "Let's make today meaningful!",
            "Action is the foundation of all success.",
            "You have the power to change your life.",
            "Small steps lead to big results.",
            "Stay positive, stay focused.",
            "Every achievement starts with the decision to try.",
            "Log in and create your future.",
            "Visualize your success and log in to start it!",
            "Your only limit is yourself; push beyond it!",
            "Success is the sum of small efforts repeated every day.",
            "Every day is a new beginning; log in and embrace it.",
            "Find your passion and turn it into purpose.",
            "Make every day your masterpiece.",
            "Log in today; your journey to greatness awaits!",
            "Don't be afraid to fail; it's a step toward success."
        ),
        "id" => array(
            "Selamat datang kembali! Siap untuk hari yang produktif?",
            "Masuk dan buat tindakanmu berarti.",
            "Siap untuk mengejar impianmu!",
            "Saatnya bertindak! Masuk untuk memulai.",
            "Setiap login adalah langkah menuju kesuksesan.",
            "Ayo, biarkan harimu mulai!",
            "Peluang baru menunggu! Silakan masuk.",
            "Siapkan dirimu untuk pencapaian yang luar biasa!",
            "Masuk untuk mewujudkan ide-ide hebatmu.",
            "Saatnya bersinar! Masuk sekarang.",
            "Kamu semakin dekat dengan tujanmu. Masuk!",
            "Hari ini adalah kesempatan emasmu!",
            "Siap untuk menghadapi tantangan baru!",
            "Langkah kecil: masuk untuk pencapaian besar.",
            "Percayalah pada dirimu dan masuk untuk masa depan.",
            "Buka potensimu dengan setiap sesi.",
            "Biarkan visi kamu menjadi panduan hari ini!",
            "Nikmati setiap momen; masuk untuk membuatnya berarti.",
            "Perjalanan menuju kebesaranmu dimulai dengan satu klik.",
            "Usahakan kemajuan, bukan kesempurnaan.",
            "Hari baru, tujuan baru, peluang baru!",
            "Setiap login adalah kesempatan untuk berubah.",
            "Rebut hari ini dan buatlah milikmu!",
            "Teruslah lapar, tetap termotivasi.",
            "Kemungkinanmu tidak terbatas; masuklah!",
            "Berani bermimpi dan masuk untuk mengambil tindakan.",
            "Motivasi adalah yang memulai kamu.",
            "Bangun kebiasaan sukses dengan setiap login.",
            "Hal-hal besar terjadi di luar zona nyamanmu.",
            "Teruslah bergerak maju; kamu hampir sampai!",
            "Fokus pada tujuan, bukan rintangan.",
            "Masuklah hari ini dan ambil langkah pertama.",
            "Waktu terbaik untuk bertindak adalah sekarang!",
            "Ubah impianmu menjadi rencana.",
            "Usahamu menentukan hasilmu.",
            "Mari kita buat hari ini berarti!",
            "Tindakan adalah fondasi dari semua kesuksesan.",
            "Kamu memiliki kekuatan untuk mengubah hidupmu.",
            "Langkah kecil mengarah ke hasil besar.",
            "Tetap positif, tetap fokus.",
            "Setiap pencapaian dimulai dengan keputusan untuk mencoba.",
            "Masuk dan ciptakan masa depanmu.",
            "Visualisasikan kesuksesanmu dan masukkan untuk memulainya!",
            "Satu-satunya batasanmu adalah dirimu sendiri; dorong dirimu!",
            "Kesuksesan adalah jumlah upaya kecil yang diulang setiap hari.",
            "Setiap hari adalah awal yang baru; masuklah dan sambutlah!",
            "Temukan hasratmu dan ubah menjadi tujuan.",
            "Buat setiap hari menjadi mahakaryamu.",
            "Masuklah hari ini; perjalanan menuju kebesaran menantimu!",
            "Jangan takut untuk gagal; itu adalah langkah menuju kesuksesan."
        ),
        'fr' => array (
            "Bon retour ! Prêt pour une journée productive ?",
            "Connectez-vous et faites en sorte que vos actions comptent.",
            "Préparez-vous à poursuivre vos rêves !",
            "Il est temps d'agir ! Connectez-vous pour commencer.",
            "Chaque connexion est un pas vers le succès.",
            "Allez, que votre journée commence !",
            "De nouvelles opportunités vous attendent ! Veuillez vous connecter.",
            "Préparez-vous à de grandes réalisations !",
            "Connectez-vous pour réaliser vos grandes idées.",
            "Il est temps de briller ! Connectez-vous maintenant.",
            "Vous êtes plus proche de vos objectifs. Connectez-vous !",
            "Aujourd'hui est votre occasion en or !",
            "Préparez-vous à relever de nouveaux défis !",
            "Un petit pas : connectez-vous pour de grandes réalisations.",
            "Croyez en vous et connectez-vous pour l'avenir.",
            "Débloquez votre potentiel à chaque session.",
            "Laissez votre vision vous guider aujourd'hui !",
            "Profitez de chaque instant ; connectez-vous pour lui donner un sens.",
            "Votre voyage vers la grandeur commence par un clic.",
            "Visez le progrès, pas la perfection.",
            "Une nouvelle journée, de nouveaux objectifs, de nouvelles opportunités !",
            "Chaque connexion est une chance de changer.",
            "Saisissez aujourd'hui et faites-en le vôtre !",
            "Restez affamé, restez motivé.",
            "Vos possibilités sont illimitées ; connectez-vous !",
            "Osez rêver et connectez-vous pour agir.",
            "La motivation est ce qui vous fait commencer.",
            "Construisez des habitudes de réussite à chaque connexion.",
            "De grandes choses se produisent en dehors de votre zone de confort.",
            "Continuez à avancer ; vous êtes presque là !",
            "Concentrez-vous sur l'objectif, pas sur les obstacles.",
            "Connectez-vous aujourd'hui et faites le premier pas.",
            "Le meilleur moment pour agir, c'est maintenant !",
            "Transformez vos rêves en un plan.",
            "Vos efforts déterminent vos résultats.",
            "Rendons cette journée significative !",
            "L'action est le fondement de tout succès.",
            "Vous avez le pouvoir de changer votre vie.",
            "De petits pas mènent à de grands résultats.",
            "Restez positif, restez concentré.",
            "Chaque réussite commence par la décision d'essayer.",
            "Connectez-vous et créez votre avenir.",
            "Visualisez votre succès et connectez-vous pour le commencer !",
            "Votre seule limite, c'est vous-même ; poussez-vous au-delà !",
            "Le succès est la somme de petits efforts répétés chaque jour.",
            "Chaque jour est un nouveau départ ; connectez-vous et accueillez-le !",
            "Trouvez votre passion et transformez-la en but.",
            "Faites de chaque jour votre chef-d'œuvre.",
            "Connectez-vous aujourd'hui ; votre voyage vers la grandeur vous attend !",
            "N'ayez pas peur d'échouer ; c'est une étape vers le succès."
        )
    );

    /**
     * 
     * @param string $locale
     * @return string
     */
    public function getMOTD ($locale='id') {
        $seed       = count ($this->messageOfTheDay['id']) - 1;
        $theLocale  = $locale;
        if (strpos($locale, '-')) {
            $t          = explode ('-', $locale);
            $theLocale  = $t[0];
        }
        $randNum    = rand (0, $seed);
        return $this->messageOfTheDay[$theLocale][$randNum];
    }
}